apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: django
spec:
  destination:
    name: ''
    namespace: django
    server: 'https://kubernetes.default.svc'
  source:
    path: ./
    repoURL: 'https://github.com/Avnshrai/django-sample-deploy.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
